name: Extract ZIP

on:
  push:
    paths:
      - "**.[zZ][iI][pP]"
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract ZIP files
        run: |
          shopt -s nullglob nocaseglob
          zip_files=(*.zip)
          
          if [ ${#zip_files[@]} -eq 0 ]; then
            echo "هیچ فایل زیپی در ریشه ریپازیتوری پیدا نشد!"
            exit 0
          fi

          mkdir -p extracted
          for f in "${zip_files[@]}"; do
            echo "در حال اکسترکت کردن: $f"
            unzip -o "$f" -d extracted
          done

      - name: Commit extracted files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add extracted
          git commit -m "Extract ZIP contents" || echo "Nothing to commit"
          git push
